export const GENRES: Record<string, string[]> = {
  "R&B": [
    "Boogie",
    "Contemporary",
    "Disco",
    "Doo Wop",
    "Funk",
    "Go Go",
    "Gospel",
    "Indie Soul",
    "Neo-Soul",
    "New Jack Swing",
    "P-Funk",
    "Psychedelic Funk",
    "Psychedelic Soul",
    "Rhythm & Blues",
    "Soul",
    "Synth Funk",
  ],

  Jazz: [
    "Acid Jazz",
    "Afro Cuban",
    "Avant-Garde",
    "Bebop",
    "Big Band",
    "Contemporary Jazz",
    "Dixieland",
    "Exotica",
    "Jazz-Funk",
    "Jazz Fusion",
    "Jazz Manouche",
    "Latin Jazz",
    "Lounge",
    "Modal Jazz",
    "New Age",
    "Post Bop",
    "Ragtime",
    "Senegalese Jazz",
    "Smooth Jazz",
    "Soul Jazz",
    "Swing",
  ],

  Blues: [
    "Boogie-Woogie",
    "Chicago Blues",
    "Country Blues",
    "Delta Blues",
    "Electric Blues",
  ],

  Classical: [
    "Ballet Music",
    "Beijing Opera",
    "Cantonese Opera",
    "Huangmei Opera",
    "March",
    "Modern Classical",
    "Opera",
    "Revolutionary Beijing Opera",
    "Shanghai Opera",
    "Shaoxing Opera",
    "Song Poetry",
    "Waltz",
  ],

  Country: [
    "Americana",
    "Bluegrass",
    "Country Gospel",
    "Honky Tonk",
    "Western",
  ],

  Electronic: [
    "Afrobeats",
    "Amapiano",
    "Ambient",
    "Balearic",
    "Breakbeat",
    "Dance",
    "Detroit Techno",
    "Downtempo",
    "Drone",
    "Drum'n'Bass",
    "Dubstep",
    "Electro",
    "Euro Dance",
    "Experimental",
    "Freestyle",
    "House",
    "Indie Dance",
    "Jungle",
    "Kuduro",
    "Kwaito",
    "Lo-Fi Beats",
    "Miami Bass",
    "Moombahton",
    "Noise",
    "Reggaeton",
    "Synth Pop",
    "Synthwave",
    "Tech House",
    "Techno",
    "Trance",
    "Trip Hop",
    "UK Garage",
  ],

  Folk: [
    "African",
    "Afrobeat",
    "Arabic",
    "Asian",
    "Caribbean",
    "Chinese",
    "English Folk",
    "Global Grooves",
    "Hungarian",
    "Indian",
    "Indie Folk",
    "Indonesian",
    "Italian",
    "Japanese",
    "Korean",
    "Mediterranean",
    "Middle Eastern",
    "Mongolian",
    "Moroccan",
    "Nigerian",
    "Paraguayan",
    "Persian",
    "Peruvian",
    "Scottish",
    "Spanish",
    "Swedish",
    "Traditional Folk",
    "Turkish",
  ],

  "Hip-Hop": [
    "Alternative Rap",
    "Beats",
    "Gangsta Rap",
    "Grime",
    "Hip Hop",
    "Latin Rap",
    "Old School Rap",
    "Rap",
    "Trap",
  ],

  Latin: [
    "Afro Latin",
    "Bachata",
    "Bolero",
    "Boogaloo",
    "Bossa Nova",
    "Brazilian",
    "Colombian",
    "Cuban",
    "Mambo",
    "Mexican",
    "Milonga",
    "Puerto Rican",
    "Rumba",
    "Salsa",
    "Samba",
    "Tamborito",
    "Tango",
    "Urban Latino",
  ],

  Pop: [
    "Adult Contemporary",
    "Alternative",
    "Ballad",
    "Indie Pop",
    "Psychedelic Pop",
    "Sunshine Pop",
  ],

  Reggae: [
    "Dancehall",
    "Dub",
    "Ska",
  ],

  Rock: [
    "Alternative",
    "Blues Rock",
    "Folk Rock",
    "Garage Rock",
    "Heavy Metal",
    "Indie Rock",
    "Kraut Rock",
    "Metal",
    "New Wave",
    "Post-Rock",
    "Prog Rock",
    "Psychedelic Rock",
    "Punk",
    "Soft Rock",
    "Surf Rock",
  ],

  Soundtrack: [
    "Anime Soundtrack",
    "Bollywood",
    "Broadway",
    "Cinematic Soundtrack",
    "Game Soundtrack",
    "Musical",
  ],
};
